# Generated by Django 2.2.6 on 2019-10-10 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import general.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=0)),
                ('auth_source', models.CharField(default='local', max_length=10)),
                ('auth_id', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('center', 'Center')], default='center', max_length=10)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=260, null=True)),
                ('is_static', models.BooleanField(default=False)),
                ('point', models.IntegerField(blank=True, default=0, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='general.Field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=0)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=260, null=True)),
                ('path_photo', models.ImageField(max_length=500, upload_to=general.models.path_and_rename, validators=[general.models.validate_file_size])),
                ('path_video', models.FileField(blank=True, default='', max_length=500, null=True, upload_to=general.models.get_video_path, validators=[general.models.validate_video_file_size])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=0)),
                ('auth_source', models.CharField(default='local', max_length=10)),
                ('auth_id', models.CharField(blank=True, max_length=100, null=True)),
                ('contribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='general.Contribute')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=0)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=260, null=True)),
                ('is_tag', models.BooleanField(default=False)),
                ('fields', models.ManyToManyField(related_name='taxonomies', to='general.Field')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='general.Taxonomy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=0)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=260, null=True)),
                ('medias', models.ManyToManyField(related_name='stacks', to='general.Media')),
                ('taxonomies', models.ManyToManyField(related_name='stacks', to='general.Taxonomy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=0)),
                ('first_value', models.CharField(blank=True, max_length=500, null=True)),
                ('second_value', models.CharField(blank=True, max_length=500, null=True)),
                ('conclusion', models.CharField(blank=True, max_length=500, null=True)),
                ('winner', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('center', 'Center')], default='center', max_length=10)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='general.Field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contribute',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributes', to='general.Round'),
        ),
        migrations.AddField(
            model_name='contribute',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('db_status', models.IntegerField(choices=[(-1, 'Deleted'), (0, 'Pending'), (1, 'Active')], default=0)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=260, null=True)),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_comparisons', to='general.Stack')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_comparisons', to='general.Stack')),
                ('rounds', models.ManyToManyField(related_name='battles', to='general.Round')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
